name: todoapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_timeline_calendar: ^1.0.9
  firebase_core: ^2.12.0
  cloud_firestore: ^4.7.0
  google_fonts: ^4.0.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  fluttertoast: ^8.2.4
  flutter_slidable: ^3.0.1
  firebase_auth: ^4.17.9
  page_transition: ^2.0.10
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.10

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
flutter_intl:
  enabled: true
